        general:
            random_state: 42
        
        model:
            library: sklearn.ensemble
            name: RandomForestClassifier
            model_params:
                n_estimators: 100
                max_depth: 10
                min_samples_split: 2
                min_samples_leaf: 2
                bootstrap: True
        
        features:
            lags: 1, 7, 10
            windows: 3, 5, 7
        
        training:
            test_size: 0.2
            cross_validation_folds: 5
        
        currency_mapping:
            BTC: 0
            ETH: 1
            LTC: 2 
        
        chosen_trained_model: rf_03.pkl
        
        output:
            model_save_path: models/best_model.pkl